version: "3.8"

# networks:
#   groupweb-prod:
#     driver: bridge

services:
  niugroup:
    container_name: niugroup
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    # - .env.production
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - groupweb-prod
    # depends_on:
    #   mysql:
    #     condition: service_healthy

  # mysql:
  #   image: mysql:8.0
  #   container_name: next-app-mysql
  #   command: --default-authentication-plugin=caching_sha2_password
  #   restart: unless-stopped
  #   # volumes:
  #   #   - ./docker/data/mysql/:/var/lib/mysql/
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin
  #     - MYSQL_DATABASE=notes
  #     - MYSQL_USER=notes
  #     - MYSQL_PASSWORD=cpZfriEBbmJjWeiR
  #   ports:
  #     - '3306:3306'
  #   healthcheck:
  #     test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306']
  #     interval: 5s
  #     timeout: 2s
  #     retries: 20
  #   networks:
  #     - groupweb-prod
